# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('books', '0001_initial'), ('books', '0002_bookcopy'), ('books', '0003_auto_20170617_1649'), ('books', '0004_auto_20170617_1649'), ('books', '0005_auto_20170617_1828'), ('books', '0006_bookcoverpreview'), ('books', '0007_auto_20170617_2139'), ('books', '0008_auto_20170617_2259'), ('books', '0009_auto_20170618_1053'), ('books', '0010_auto_20170624_1152'), ('books', '0011_auto_20170624_1205')]

    initial = True

    dependencies = [
        ('libraries', '0007_auto_20170617_1500'),
        ('accounts', '0003_auto_20170612_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1500)),
                ('page_count', models.PositiveSmallIntegerField()),
                ('cover', models.ImageField(blank=True, upload_to='cover/')),
                ('author', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together=set([('title', 'author')]),
        ),
        migrations.CreateModel(
            name='BookCoverPreview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
            ],
        ),
    ]
