# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170612_2216'),
        ('books', '0005_auto_20170617_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCoverPreview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
            ],
        ),
    ]
