# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_bookcoverpreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
