# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20170617_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(max_length=1500),
        ),
    ]
