# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0007_auto_20170617_1500'),
        ('books', '0008_auto_20170617_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcopy',
            name='library',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='libraries.Library'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(upload_to='cover/'),
        ),
        migrations.AlterField(
            model_name='googlebook',
            name='ISBN',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='googlebook',
            name='google_id',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
