# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20170618_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='google_info',
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, upload_to='cover/'),
        ),
        migrations.DeleteModel(
            name='GoogleBook',
        ),
    ]
