# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20170624_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcopy',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookcopy',
            name='library',
        ),
        migrations.DeleteModel(
            name='BookCopy',
        ),
    ]
