# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 14:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('libraries', '0001_initial'), ('libraries', '0002_auto_20170613_1931'), ('libraries', '0003_auto_20170613_2140'), ('libraries', '0004_auto_20170613_2322'), ('libraries', '0005_auto_20170613_2326'), ('libraries', '0006_auto_20170614_0024'), ('libraries', '0007_auto_20170617_1500'), ('libraries', '0008_bookcopy_lending'), ('libraries', '0009_auto_20170624_1458'), ('libraries', '0010_auto_20170624_1531'), ('libraries', '0011_auto_20170624_1654'), ('libraries', '0012_auto_20170624_1704'), ('libraries', '0013_auto_20170624_2308'), ('libraries', '0014_auto_20170625_1018'), ('libraries', '0015_auto_20170625_1351'), ('libraries', '0016_auto_20170627_2255'), ('libraries', '0017_reading')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
        ('accounts', '0003_auto_20170612_2216'),
        ('books', '0011_auto_20170624_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_name_default', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'libraries',
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraries.Library')),
                ('confirmation_code', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together=set([('library', 'email')]),
        ),
        migrations.AddField(
            model_name='library',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='libraries', to='accounts.UserProfile'),
        ),
        migrations.AlterField(
            model_name='library',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='owner', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='library',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='owner', serialize=False, to='accounts.UserProfile'),
        ),
        migrations.AlterField(
            model_name='library',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='home_library', serialize=False, to='accounts.UserProfile'),
        ),
        migrations.AlterField(
            model_name='library',
            name='name',
            field=models.CharField(default='Home Library', max_length=40),
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraries.Library')),
            ],
        ),
        migrations.CreateModel(
            name='Lending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lend_date', models.DateTimeField(auto_now_add=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libraries.Library')),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraries.BookCopy')),
            ],
        ),
        migrations.AddField(
            model_name='bookcopy',
            name='comment',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='libraries.Library'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraries.Library'),
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libraries.Library'),
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraries.BookCopy')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
            ],
        ),
    ]
