# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0002_auto_20170613_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraries.Library')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together=set([('library', 'email')]),
        ),
    ]
