# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 23:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libraries', '0003_auto_20170613_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='confirmation_code',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='library',
            name='users',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='library',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='owner', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
