# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 23:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0004_auto_20170613_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='owner', serialize=False, to='accounts.UserProfile'),
        ),
        migrations.AlterField(
            model_name='library',
            name='users',
            field=models.ManyToManyField(related_name='users', to='accounts.UserProfile'),
        ),
    ]
