# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0006_auto_20170614_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='name',
            field=models.CharField(default='Home Library', max_length=40),
        ),
        migrations.AlterField(
            model_name='library',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='libraries', to='accounts.UserProfile'),
        ),
    ]
