# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0008_bookcopy_lending'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcopy',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='lending',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libraries.Library'),
        ),
    ]
