# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0012_auto_20170624_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lending',
            name='lend_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
