# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0013_auto_20170624_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lending',
            name='copy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='libraries.BookCopy'),
        ),
    ]
