# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 22:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0015_auto_20170625_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcopy',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libraries.Library'),
        ),
    ]
