# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_registration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='confirmation_code',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
